//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorcado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escalafon
    {
        public int Identificacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Marcador { get; set; }
        public Nullable<int> Ganadas { get; set; }
        public Nullable<int> Perdidas { get; set; }
    }
}
