//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorcado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intento
    {
        public int IntentoID { get; set; }
        public int PartidaID { get; set; }
        public string Letra { get; set; }
        public bool EsCorrecta { get; set; }
        public System.DateTime FechaIntento { get; set; }
    
        public virtual Partida Partida { get; set; }
    }
}
