//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorcado.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AhorcadoDBEntities : DbContext
    {
        public AhorcadoDBEntities()
            : base("name=AhorcadoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Intento> Intento { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<Palabra> Palabra { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Escalafon> Escalafon { get; set; }
    }
}
