//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorcado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Palabra()
        {
            this.Partida = new HashSet<Partida>();
        }
    
        public int PalabraID { get; set; }
        public string Texto { get; set; }
        public string TextoNormalizado { get; set; }
        public bool TieneTilde { get; set; }
        public bool Usada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partida> Partida { get; set; }
    }
}
