//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorcado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partida()
        {
            this.Intento = new HashSet<Intento>();
        }
    
        public int PartidaID { get; set; }
        public int JugadorID { get; set; }
        public int PalabraID { get; set; }
        public string Nivel { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public int DuracionSegundos { get; set; }
        public string Resultado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intento> Intento { get; set; }
        public virtual Jugador Jugador { get; set; }
        public virtual Palabra Palabra { get; set; }
    }
}
